### ISSUE TITLE
experimental-gls should work for polyploids

### ISSUE THREAD

**Issue by ekg** [ekg/freebayes#125]
The `--experimental-gls` parameter produces much better genotyping accuracy, and thus site detection accuracy in diploid humans.

Some issues with the implementation prevent its use for polyploids, which is a common-enough use-case for freebayes that I have not set it as default.

If these can be resolved then I will set it as the default, which will yield improved performance of the defaults.

A related consideration is if it should always handle mapping quality. In some contexts, this is not informative. Perhaps it should be assumed to be informative, and this can be turned off as-needed by users.

**Comment by mdshw5** [comment]
I think the case where mapping quality is not *quantitative* might be more important, since you want the genotype quality scores to be a quantitative value. Specifically, you might special-case a MAPQ of 255, since this usually indicates a unique alignment (bowtie1 & 2) instead of a quantitative value.

**Comment by swheelan** [comment]
I agree; particularly when dealing with large datasets produced on diverse platforms over time, it's important to be able to either turn off consideration of mapping qualities, or to use them in ways that are meaningful. Whichever choice is made needs to be explicit so that the user doesn't risk creating misleadingly high quality variant calls (I'd prefer the default to be ignoring mapping quality as it is reported so inconsistently by alignment programs). BTW I have validated polyploid datasets for testing.

Related (sort of) -- the large datasets referred to above are from mixed platforms and thus have mixed phred scales. We should have been smart enough to realize this and rescale but it might be sensible for freebayes to check as well.

**Comment by ekg** [comment]
This has been resolved. If you need to turn of the new model, use `--legacy-gls`. The flag `--experimental-gls` has been removed.
