### ISSUE TITLE
RG tags

### ISSUE THREAD

**Issue by agolicz** [ekg/freebayes#157]
Hello,

I was wondering how does freebayes use RG tags internally. I have some old merged bam files where multiple lanes from the same library and sample or multiple libraries from the same sample were combined. The RG tag distinguishes only samples (same RG tag for all runs and libraries from the same sample). Will that be a problem? Does freebayes use lane/library information or only sample?

Best wishes,
Agnieszka

**Comment by ekg** [comment]
Each RG group is part of a SM (sample). `freebayes` uses the RG group tags
to determine sample, but that's it. Then the data from each sample is
pooled together.

You can (if you're obsessed with genotype likelihoods) use per-RG
contamination estimates from something like VerifyBAMid. Otherwise
freebayes doesn't touch the specific RGs.

**Comment by agolicz** [comment]
Great! Thanks very much. I'm closing this issue.
