### ISSUE TITLE
How can we help you with Freebayes and vcflib ?

### ISSUE THREAD

**Issue by tseemann** [ekg/freebayes#162]
Erik

Like you I am an author (and maintainer!) of some popular piece of software and I understand the pressure to address github Issues when we'd rather be working on other things.

It's clear a lot of people love and depend on Freebayes and vcflib. My question is: how can we, the community, help to carry some of the burden associated with these projects?

I am trying to work on getting them packaged in Brew and LinuxBrew (and possibly APT/RPM) to help solve the "can't install" problems you get (inevitable for such a modular tool). 

Is there anything else we can do?

Torsten.

**Comment by ekg** [comment]
Hi @tseemann,

The biggest problem I have is that I'm the sole maintainer of these projects. I have had tremendous help in testing, but very little in actually developing or maintaining things at code or distribution level.

I think this is a typical situation with bioinformatic tools, which are often written in high-performance languages like C or C++, but frequently used by people without experience working in or reading these languages. It's an odd situation, because many of the users are actually great programmers in their own, but have focused on languages which are faster to develop prototypes and use for scripting (python, perl, and shell) and don't feel comfortable contributing patches.

I am working full-time on a wet lab project and a graph-based system for genomics [vg](https://github.com/ekg/vg). freebayes remains incredibly useful, and I don't want to drop support for it. The rate of citations seems to be accelerating, and I am familiar with a wide amount of use in industry. The rise of ensemble calling methods as developed by @chapmanb and others has ensured that although it is not the most-popular variant caller, freebayes is frequently used in genomic analysis pipelines. As such, I am committed to helping continue its development.

There are a lot of specific developments that could be helpful, but probably the most basic involve distribution-level support. It would be great if freebayes were in debian and fedora package systems, in addition to the OSX-based ones. Establishing a stream of stable, packaged source and binary distributions would be tremendously helpful. Similarly helpful would be developing and contributing tests (which some have already done, thanks!). If you or anyone else is interested in doing these kinds of things, I can add you to this repository as a committer.

Beyond this, there are actual algorithmic improvements that could further enhance the performance of the system. In the medium term, I'd like to roll back developments from vg into freebayes. I the shorter-term, there are a few changes that will help a lot with calling difficult variants. A specific one would be adjusting the `--min-repeat-entropy` system to be left-right balanced (at present it is directionally biased). This would allow us to set this as default and establish a new standard for haplotype-based genotyping performance.

For it to survive (and survive well), freebayes needs to grow up as an open source project. Typically, a major step is when maintenance and development work begins to be shared by a group rather than the original author. I'm happy to help guide this process, but encourage anyone who is interested in learning more about this kind of system or in adding features to one to think of freebayes as an open platform for experimentation and development of novel approaches to processing short read data. If you are a student who wants to write a variant caller, consider

If this is interesting to anyone I will be happy to support, and will work (as I am now) to simplify the internals of the system so that it can be more readily modified.

Hope this explains,

-Erik

**Comment by chapmanb** [comment]
Erik and Torsten;
This is a great discussion. Erik, I appreciate all the work you've done on FreeBayes and all of the excellent support you provide. It's unfortunate that crucial work like continued support and development are not widely appreciated. As normal, Vonnegut captures it perfectly: http://www.goodreads.com/quotes/276615-another-flaw-in-the-human-character-is-that-everybody-wants

I'm agreed that it would be awesome to have more of a shared community handling these issues. C/C++ may be part of the barrier (I personally am terrible at C++) but it's also challenging in general to be able to pick out the best place to get started for a fix on someone else's code base. If you're able to give folks potential locations to dig into, that might help others be able to submit patches. I often read your fixes to try and learn for next time.

I appreciate all the work on FreeBayes and look forward to continuing to develop a community around it and your new variant graph work.

**Comment by tseemann** [comment]
@chapmanb Good to know you are a Vonnegut fan; I voraciously read all his books during my formative years!
