### ISSUE TITLE
Intermittent truncation of calls when using targets BED input

### ISSUE THREAD

**Issue by chapmanb** [ekg/freebayes#173]
Erik;
Thanks so much for the work and the most recent updates. Those fixed the issues with target regions and min_entropy (#165) but unfortunately did not resolve the underlying issue with loss in sensitivity that I saw with the latest versions. Sorry, I was hoping the previous test case would sort everything out.

I dug into the issue more with the latest head (v0.9.21-18: c15a283) and it looks like there is a problem with some regions causing FreeBayes to halt calling, truncating the output when you have multi-region target BED files. I put together a small test example demonstrating the problem:

https://s3.amazonaws.com/chapmanb/fb/freebayes_truncated.tar.gz

(as before, this has a little shell script that shows the problem with included data, and only needs a pointer to a local copy of the GRCh37 reference)

The problematic region, 1:41905-41945 in regions-missing.bed, results in FreeBayes stopping calling for the remaining intervals in the targets file. There are no obvious errors even with debug turned on. This truncating causes sections to get lost, since I'm using BED files of multiple regions, leading to the loss in sensitivity.

I don't yet understand the conditions that cause FreeBayes to stop calling. It happens on ~1/3 of our targets file so is relatively common but not universal. Hopefully the test case provides more of a clue for you.

The last version that validated well was 0.9.21-7 (https://github.com/ekg/freebayes/commit/7dd41dbc8c789d5a82288bbafc983ad525f04061) and I've tested on 0.9.21-13 (https://github.com/ekg/freebayes/commit/c5efe19a4eb40ce6c1f6ef82c67bb766d319c0f6) and later which all show this symptom.

Happy to provide any more details that would be helpful. Thanks again.

**Comment by ekg** [comment]
@chapmanb I'm going to work on this now. Sorry for the continued difficulties.

As a (very passable) workaround you can run freebayes over the list of targets using the same pattern seen in [freebayes-parallel](https://github.com/ekg/freebayes/blob/master/scripts/freebayes-parallel). The result will be correct behavior and faster runtime. I'm sorry for the difficulty with using BED targets, but this is simply not a way that I've run the method since the first few months of development. I'd either run whole-genome and then filter down, or run using GNU parallel over the list of targets.

**Comment by jpuritz** [comment]
I'll chime in here, at least in supporting the use of BED targets.  For RAD sequencing with de novo loci, the reference ends up being thousands of short fragments (200 bp) each of which is generally an entire target.  Generally, we loading dozens to hundreds of bam files into FreeBayes, so there is some startup overhead involved.  With the targets option, it becomes a bit cumbersome because it basically has to call an instance of FB for each RAD fragment.  I found that it was more efficient to break up the reference using 50-100 BED target chunks and use this for GNU-parallel.  I'd guess that this would be the same for RNA/transcriptomics as well.  

As always, we all appreciate your work on freebayes!

**Comment by srp33** [comment]
I've see similar behavior to what Brad describes.

**Comment by ekg** [comment]
Could anyone else test this out? The git HEAD has been passing @chapmanb 's test for some time, but I forgot to refer to this issue in the commit.

**Comment by chapmanb** [comment]
Erik;
Thanks much for the heads up. Apologies for missing that you'd fixed this. I updated to the latest and ran validation tests for 0.9.21-26 (the latest git HEAD) versus 0.9.21-7, which we're using in bcbio. The latest runs cleanly, does not have this problem, and has similar sensitivity and precision to the 0.9.21-7. Here is a validation on hg19 and hg38 of the two versions:

http://imgur.com/a/GXR5O

Thanks much for fixing this. It's great to be back tracking the latest version.

**Comment by ekg** [comment]
Hi Brad, thanks for double-checking this! I have a question about the
results--- what's going on with indels and hg38 vs hg19? Why is the FN rate
so much lower for all the callers?

**Comment by chapmanb** [comment]
Erik;
I'm not sure -- it might be an issue with the truth sets. The hg38 truth sets, both lifted over Genome in a Bottle and the natively generated Illumina Platinum Genomes, have more indels detected (good) but not as high a percentage validate (bad). I'm enthused by the extra detection capability but hopefully we can refine the truth sets to figure out what is going on as folks get more into 38 work. There is more background in the post here: http://bcb.io/2015/09/17/hg38-validation/
