### ISSUE TITLE
Variant Calling from pre and post cancer treatment patients with no matched normal without matched normal

### ISSUE THREAD

**Issue by yaseen-ladak** [ekg/freebayes#208]
I need some suggestion on using freebayes. I have a patients DNA  whole exome seq data pre and post treatment. I don’t have their matched normal. The goal is to find if the treatment has cause a change in their exome after treatment.
Can you please advise me on the approach to take on this? How can I use freebayes for this.  I have the aligned and sorted BAMS. I have aligned all the FASTQ files to hg38. I know how to use freebayes for each sample against the hg 38 but I don’t know how can I use freebayes for this. I know there are other variant callers like varscan that perhaps have a built in options to do this, but I would like stick to freebayes.
Regards,
Yaseen

Yaseen

**Comment by ekg** [comment]
@AlistairNWard Do you have a pipeline for this set up in gkno?

**Comment by ekg** [comment]
@yaseen-ladak I completely forgot to mention, there is a framework which uses freebayes for somatic variant calling. It should be very user-friendly, very fast, and is also documented in a recent publication: [speedseq](https://github.com/hall-lab/speedseq). Please let me know how you get on with this. @cc2qe and the @hall-lab have done a fantastic job with it. You may need some guidance on how to handle your situation (lacking a matched normal). There may be an approach you can use, but it's hard to say. I guess that you can use the two tumor samples at different time points in the place of normal (1st sample) and tumor (2nd sample).

**Comment by AlistairNWard** [comment]
We have never done any calling on tumors without a matched normal, so there
is no specific pipeline in gkno to handle this case. It would be great to
build a pipeline with scientifically deduced parameters that could be built
into gkno so that others performing similar analyses would have a
justifiable starting point.

Yaseen, if you would like to discuss using gkno pipelines, please contact
me (AlistairNWard@gmail.com). There are pipelines available for calling
with Freebayes and we could look at modifying the parameters within them,
or build new pipelines if necessary that can then be shared with the
community.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by yaseen-ladak** [comment]
@ekg and @AlistairNWard 

Question:
I have two sets of whole exome sequence data from 50 patient cohorts. Pre chemo and post chemo. I want to find out if giving a chemo has caused any changes in the exome of patients. 
I just need the freebayes steps and I have a pipline that i build my self. 

1. How would you use freebayes if I had a matched normal and a cancer sample, would you please give me the exact command to handle this. Can freebayes take two inputs one from matched normal and one from tumor?  Say I had 50 patients with matched normal and with same kind of tumor. Would this mean that I would need run this command 50 times or is there a way I can combine all the matched normals to one and all the tumors to one? The get one final VCF. or if I run 50 times then I get 50 VCF for each patient.

What does this command mean I saw in one of the post for somatic calling:

freebayes -f ref.fa --pooled-continuous --pooled-discrete -F 0.03 -C 2 tumor.bam normal.bam >out.vcf

2. The second question is since I dont have the matched normal. Does the following sound well or what are the drawbacks:
Generate VCF from pre treatment chemo with hg38 as normal
Generate VCF from post treatment chemo with hg38 as normal.
Check if the Variant present in post VCF file is in pre sample so as to rule out that it is not cause of the variation in hg38 but actually due to change in the pre treatment exome.

Do I need to this 50 times or would it be better  combine pre-treatment samples as one and post treatment samples as one. How do I actually generate a combined pre-treamtnet set or post is it at BAM or one just uses cat command to combine all the raw FASTQ from pre treated samples i.e. 50.

I really need your help guys and I would be happy to share the broader results and not the specifics with the community.

Thanks,
Yaseen

**Comment by AlistairNWard** [comment]
Hi Yaseen, I can give you my advice, but include the caveat that running
cancer analyses is not my primary function, so you should try and get
advice from cancer specific analysts. If anything I say here is off base,
please correct me!

Freebayes can take as many inputs files as you give it. Just specify all
the files on the command line and you can give it as many bams as you like.
It is advisable to call as a population, rather than as individuals, since
freebayes will consider all evidence together, which can effect the
probability of genotypes it gives for other samples. For example, if one
sample is a het for a variant, but it's a borderline case, freebayes will
likely give it a very low quality. If the same variant is seen in all the
other samples, it becomes more likely that the variant is real, and this
will be evident in the quality score and can save calls that would
otherwise have been missed or filtered out.

You would only need to run the command line once, but it will take a while
to run, so I would recommend splitting the job up by calling in small
genomic regions (by defining the --region argument). This is somewhere
where using gkno can be helpful. You can specify lists of regions, so you
still would only need a single command line. gkno will also combine all the
resulting regional vcfs so that the end result is a single vcf file with
all samples. You can also look at freebayes parallel to help with this.

*IMPORTANT*
Make sure that when you did the alignments, you specified read groups for
the all the data. People often forget this, but it is critical that each
sample has a unique read group so that freebayes can identify which reads
belong to which sample. Without this, you will not get individual genotypes
and genotype likelihoods for all samples, which will stop your analysis in
its tracks.

For calling somatic variants (and in line with speedseq), I use the
following command line:

freebayes -f ref.fa -C 2 -F 0.12 --pooled-continuous --pooled-discrete -a
--report-genotype-likelihood-max --genotype-qualities --use-duplicate-reads
pre1.bam pre2.bam ... post1.bam post2.bam ...

Some of these parameters depend on the depth and quality of your exome
data. I typically include dpulicate reads when using deep exome data, since
the high depth means it is likely that independent fragments appear as
duplicates when using reads <150 bp. The -C and -F define the minimum
number (fraction) of alt alleles required in a single sample, in order to
consider the alternate allele. Depending on the clonal structure of your
tumour samples, these may need adjusting. -F 0.12 means that one sample
must have at least 12% of the reads supporting the alt allele. If the
tumour has multiple sub-clones and the variant is a het, it is possible you
would need to go lower, but this is a good starting point. @ekg can
probably give more insight into the pooled commands, but these stem from
the fact that your tumours are essentially pooled sequences (from the
subclones), rather than straight germline tissue from a single sample.

You could do multiple experiments. The one you suggest; call all
pre-treatment tumours together, then call all post-treatment tumours
together and compare the two resulting VCF files looking for variants
present in the pre-treatment that are gone from the post. Similarly, you
could look at those variants that survive. One think to keep in mind is
that the chemo could have killed many subclones, and only those with
chemo-resistance survive. In this case, very low frequency variants from
the pre-treatment samples could have risen to prominence.

You could also call all samples together (in this case, it would be wise to
have ordered your samples on the command line as above, so that all
pre-treatment samples are supplied, then all post-treatment). You could
then use tools such as cyvcf2 to interrogate the genotypes of all samples
and look for trends between variants in the two sets of data.

I hope that this of some use.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by yaseen-ladak** [comment]
@AlistairNWard @ekg 

@ekg  --> Can you please give me some summary of --pooled-continuous --pooled-discrete -a --report-genotype-likelihood-max --genotype-qualities 

@AlistairNWard ,  Thank you a million. Based on your suggestions I am making the following pipeline. Lots of it is already made but does need some setting based on what you reply to this email.

My be some silly questions but I need help :(

Just wanted to make sure I understood the things, please correct me if I am wrong. I doing this study for 50 patients with whole exome seq data. I have pre treatment and post treatment whole exome data. The question is what are the variations in post treatment exome from the pre treatment exome data.

The pipeline I am making is as follows:

1. Quality control the raw FASTQ files but keep the duplicate reads and trim the reads on quality score

2. Would Freebayes need BAMs aligned to hg38.fa (as this is my reference genome sequence even though I am doing a whole exome seq) or just convert the quality controlled FASTQs from step 1 to BAMs without aligning to hg38.fa?

 If need alignment aligned BAMs then each of the pre and post pair of FASTQ from each patient using Bowtie2/Bwa would be generated 

pre1.bam, pre2..pre50.bam  --> for 50 patients
post1.bam post2.bam.. post50.bam  --> for 50 patients
    
3. Co-ordinate sort and index the BAMs from step 2 i.e. total 100 BAM files

4. Adding read groups using Picard:
  java -jar $picard/AddOrReplaceReadGroups.jar INPUT=pre1.bam OUTPUT=pre1.rg.bam RGSM=pre1

--> do this in a loop for all 50 pre treatment samples i.e. till pre50.bam

 java -jar $picard/AddOrReplaceReadGroups.jar INPUT=post1.bam OUTPUT=post1.rg.bam RGSM=post1
--> do this in a loop for all 50 pre treatment samples i.e. till post50.bam

5. Calling freebayes:

Option 1:

freebayes -f hg38.fa -C 2 -F 0.12 --pooled-continuous --pooled-discrete -a --report-genotype-likelihood-max --genotype-qualities --use-duplicate-reads pre1.bam pre2.bam ... post1.bam post2.bam

Do reads pre1.bam pre2.bam ... post1.bam post2.bam have they been aligned to the hg38 and obtained from step3? Also in this case I will get a single VCF that will show me the difference between pre-treatment BAMs and post-treatment-BAM's? I am just worried this method will think pre and post samples as one and compare it to hg.38 as we have mentioned the reference genome hg38.fa. How will freebayes know when the pre-treatment BAM’s end and post-treatment-BAMs start.

If I had a matched normal for each patient with pre and post treatment how would the call to freebayes change in this option 1.

Option2:

In your last reply you sad  “You could do multiple experiments. The one you suggest; call all pre-treatment tumours together, then call all post-treatment tumors together and compare the two resulting VCF files looking”

You meant running the freebayes command as follows two times to generate two VCF from pre-treatment and post treatment:

freebayes -f hg38.fa -C 2 -F 0.12 pre1.bam pre2.bam ..pre50.bam  --> get pre-treatment-VCF

freebayes -f hg38.fa -C 2 -F 0.12 post1.bam post2.bam .. post50.bam  --> get post-treatment-VCF

Then  from the post-treatment-VCF variants look if the variants are present in pre-treatment-VCF as the variants in post-treatment-VCF could have also come from the reference genome rather than from pre-treatment-VCF. The question is if the exome of pre-treatment chemo changes after chemo. We need to compare pre-treatment with post treatment exome and not with hg38.

Thanks,
Yaseen

**Comment by ekg** [comment]
@yaseen-ladak Let's see if we can improve the documentation here:

via `freebayes --help`:

If you just want to see output for every single allele that passes the input filters (-F, -C, and other things listed in `input filters` in the help output):

```
   -K --pooled-continuous
                   Output all alleles which pass input filters, regardles of
                   genotyping outcome or model.
```

If you have a known number of samples (and thus a known number of copies of the genome) but I don't know which reads come from which sample, set this and use --ploidy to define the number of genome copies in the pool:

```
   -J --pooled-discrete
                   Assume that samples result from pooled sequencing.
                   Model pooled samples using discrete genotypes across pools.
                   When using this flag, set --ploidy to the number of
                   alleles in each sample or use the --cnv-map to define
                   per-sample ploidy.
```

If you want to get a GQ estimate for each sample genotype call, which is defined as the marginal probability of that particular genotype for that particular sample under the model posterior:

```
   -= --genotype-qualities
                   Calculate the marginal probability of genotypes and report as GQ in
                   each sample field in the VCF output.
```

If you would like the genotypes to be assigned as `argmax(G, P(D|G))` with `G` being a genotype and `D` being the read evidence. `P(D|G)` is the probability of the data given a genotype, which is the "data likelihood":

```
   --report-genotype-likelihood-max
                   Report genotypes using the maximum-likelihood estimate provided
                   from genotype likelihoods.
```

**Comment by AlistairNWard** [comment]
In order to use Freebayes, you will need to align all your fastq files
against a reference (e.g. GRCh38). Freebayes with then look at the pileup
of reads and determine what haplotypes are present and then determine the
genotype of each sample at that locus. When you perform the alignment with
bwa, you need define read groups. This way, freebayes will know which reads
come from which sample and if you call all 100 samples together, you will
get 100 genotypes at each variant position. If you also have matched
normals, you can include those on the command line and freebayes will give
you a VCF file with more samples with their own genotypes.

The VCF file won't show you the difference between your pre- and post-
treatment exomes. What it will give you is all locations where there is
evidence for variation. You will also have the genotypes of all samples
called and you can then ask questions about these genotypes. If you are
looking for all variants present in pre-treatment that are still present in
post-treatment, you can query the genotypes at each locus and ask that the
genotype of sample1-pre = sample1-post etc.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by yaseen-ladak** [comment]
@ekg @AlistairNWard 
A quick question, as Alistair had suggested to call all the BAMS on one line I will try that after adding the read groups. My only question is does Freebayes read all the BAM files in RAM or does it rely on caching files. As I have 50 patients I would be having 100 files for pre and post treatment and that just not be possible for me to read into RAM at ones. Just wont to know if Freebayes would cache or read all at once into the RAM?

**Comment by ekg** [comment]
It only reads the amount of data it needs to to store all reads at a single
position (or a "locus" which might be up to a few tens of bases long). This
is typically not too much, and in principle you can work with several
million-fold coverage data sets without problems.

**Comment by yaseen-ladak** [comment]
@ekg @AlistairNWard 

Hello Alistair and EKG,

I am using the following command to get th VCF. I also added the read groups using picard after I had sorted the BAM files that were aligned to hg38.fa. This is just a test files for sample_1, sample 2 and hg38.fa. I ran freebayes with default parameters in my first run.

1. I am not able to see sample 1 only sample 2 is present in the VCF output?
2. Also my REF comes from hg38.fa? So in this case it is mentioned that AT changes to TC or GT in sample_2?

************************************************************

freebayes -f hg38.fa rg_sorted_aligned_sample_1.bam rg_sorted_aligned_sample_2.bam > test_6.vcf

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample_2
readseq-I20150421-153209-0786-82917222-es_sequence_1    489     .       AT      TC,GT   133.14  .       AB=0.25,0.75;ABP=7.35324,7.35324;AC=1,1;AF=0.5,0.5;AN=2;AO=2,6;CIGAR=2X,1X1M;DP=8;DPB=4293;DPRA=0,0;EPP=7.35324,16.0391;EPPR=0;GTI=0;LEN=2,1;MEANALT=2,

*********************************************************************************

**Comment by ekg** [comment]
Please do:

samtools -h file.bam | head -10000 | grep ^@RG

On your two files.

Do you see if there is a conflict in the read groups or sample names?

**Comment by ekg** [comment]
Your interpretation of the call is correct.

The reference is AT and the call includes TC and GT alleles in genotypes.

**Comment by yaseen-ladak** [comment]
@ekg @AlistairNWard 


Question 1
 The reference Allel is comming from hg38.fa since I used that as the reference. The oputput AT	changing to TC,GT means there is a base change of both AT to TC and GT why did it not show as Ref A change to T,G and Ref T changes to C,T as two different rows? also the position 489 is the position of A from the reference AT on the hg38.fa?

*********************************************************************
Question 2: 

samtools view -h rg_sorted_aligned_sample_1.bam | head -10000 | grep ^@RG
@RG	ID:1	PU:sample_1	LB:sample_1	SM:sample_1	PL:illumina_hi-seq

samtools view -h rg_sorted_aligned_sample_2.bam | head -10000 | grep ^@RG
@RG	ID:1	PU:sample_2	LB:sample_2	SM:sample_2	PL:illumina_hi-seq

Then I ran freebayes on the files above with following combinations:

freebayes -f hg38.fa rg_sorted_aligned_sample_1.bam > test_1.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1

freebayes -f hg38.fa rg_sorted_aligned_sample_2.bam > test_2.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_2
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	A	G	59.235	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3;CIGAR=1X;DP=4;DPB=4;DPRA=0;EPP=9.52472;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=42;MQMR=0;NS=1;NUMALT=1;ODDS=7.37776;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=96;QR=0;RO=0;RPP=9.52472;RPPR=0;RUN=1;SAF=3;SAP=9.52472;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina_hi-seq=1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/1:4:0:0:3:96:-5,-0.90309,0

freebayes -f hg38.fa rg_sorted_aligned_sample_1.bam rg_sorted_aligned_sample_2.bam > test_3.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	AT	TC,GT	81.9175	.	AB=0.4,0.6;ABP=3.44459,3.44459;AC=1,1;AF=0.5,0.5;AN=2;AO=2,3;CIGAR=2X,1X1M;DP=5;DPB=4093.5;DPRA=0,0;EPP=7.35324,9.52472;EPPR=0;GTI=0;LEN=2,1;MEANALT=2,2;MQM=42,42;MQMR=0;NS=1;NUMALT=2;ODDS=5.20755;PAIRED=1,1;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=65,96;QR=0;RO=0;RPP=7.35324,9.52472;RPPR=0;RUN=1,1;SAF=2,3;SAP=7.35324,9.52472;SAR=0,0;SRF=0;SRP=0;SRR=0;TYPE=mnp,snp;technology.illumina_hi-seq=1,1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/2:5:0:0:2,3:65,96:-5,-5,-5,-5,0,-5

freebayes -f hg38.fa rg_sorted_aligned_sample_2.bam rg_sorted_aligned_sample_1.bam > test_4.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_2
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	AT	TC,GT	81.9175	.	AB=0.4,0.6;ABP=3.44459,3.44459;AC=1,1;AF=0.5,0.5;AN=2;AO=2,3;CIGAR=2X,1X1M;DP=5;DPB=4093.5;DPRA=0,0;EPP=7.35324,9.52472;EPPR=0;GTI=0;LEN=2,1;MEANALT=2,2;MQM=42,42;MQMR=0;NS=1;NUMALT=2;ODDS=5.20755;PAIRED=1,1;PAIREDR=0;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=65,96;QR=0;RO=0;RPP=7.35324,9.52472;RPPR=0;RUN=1,1;SAF=2,3;SAP=7.35324,9.52472;SAR=0,0;SRF=0;SRP=0;SRR=0;TYPE=mnp,snp;technology.illumina_hi-seq=1,1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/2:5:0:0:2,3:65,96:-5,-5,-5,-5,0,-5


Some how it does fine on individual files, but when I combine sample_1 and sample_2 it only show me the first bam file i.e. if I put sample_1.bam and then sample_2.bam  as freebayes input then in VCF it shows sample_1 and not sample_2 and when I reverse the input order then I get sample_2 and not sample_1

******************************

**Comment by yaseen-ladak** [comment]
@ekg @AlistairNWard 

There is a similar query on google groups. It seems to be calling variants only from the first BAM file?

**Comment by AlistairNWard** [comment]
No, it's pulling in the reads from all the files, but both of your read
groups have the same ID. Each read points to a read group ID, which it then
identifies in the header and assigns the sample. All of your reads belong
to a read group with ID:1, so there is no way for Freebayes to know which
sample the read belongs to. You have to have unique read group ids.


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by ekg** [comment]
You can fix the read group ids with: https://github.com/ekg/bamaddrg

**Comment by yaseen-ladak** [comment]
@AlistairNWard  @ekg 

I have added the read Id. sample_2 and sample_3 are the same samples but I have made the copy from sample_2 and changed the read groups for testing.Please check below:

samtools view -h rg_sorted_aligned_sample_2.bam | head -10000 | grep ^@RG
@RG	ID:sample_2	PU:sample_2	LB:sample_2	SM:sample_2	PL:illumina_hi-seq

samtools view -h rg_sorted_aligned_sample_1.bam | head -10000 | grep ^@RG
@RG	ID:sample_1	PU:sample_1	LB:sample_1	SM:sample_1	PL:illumina_hi-seq

sorted_indexed_aligned_bam: samtools view -h rg_sorted_aligned_sample_2.bam | head -10000 | grep ^@RG
@RG	ID:sample_2	PU:sample_2	LB:sample_2	SM:sample_2	PL:illumina_hi-seq

samtools view -h rg_sorted_aligned_sample_3.bam | head -10000 | grep ^@RG
@RG	ID:sample_3	PU:sample_3	LB:sample_3	SM:sample_3	PL:illumina_hi-seq

*************************************************************
freebayes -f hg38.fa rg_sorted_aligned_sample_2.bam > test_1.vcf

tail test_1.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_2
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	A	G	59.235	.	AB=0;ABP=0;AC=2;AF=1;AN=2;AO=3;CIGAR=1X;DP=4;DPB=4;DPRA=0;EPP=9.52472;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=42;MQMR=0;NS=1;NUMALT=1;ODDS=7.37776;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=96;QR=0;RO=0;RPP=9.52472;RPPR=0;RUN=1;SAF=3;SAP=9.52472;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina_hi-seq=1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/1:4:0:0:3:96:-5,-0.90309,0

freebayes -f hg38.fa rg_sorted_aligned_sample_1.bam rg_sorted_aligned_sample_2.bam > test_2.vcf

tail test_2.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_1	sample_2
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	A	G	59.2394	.	AB=0;ABP=0;AC=4;AF=1;AN=4;AO=3;CIGAR=1X;DP=5;DPB=5;DPRA=4;EPP=9.52472;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=42;MQMR=0;NS=2;NUMALT=1;ODDS=6.56683;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=96;QR=0;RO=0;RPP=9.52472;RPPR=0;RUN=1;SAF=3;SAP=9.52472;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina_hi-seq=1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/1:1:0:0:0:0:0,0,0	1/1:4:0:0:3:96:-5,-0.90309,0


freebayes -f hg38.fa rg_sorted_aligned_sample_2.bam rg_sorted_aligned_sample_3.bam > test_3.vcf

tail test_3.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample_2	 sample_3
readseq-I20150421-153209-0786-82917222-es_sequence_1	489	.	A	G	118.465	.	AB=0;ABP=0;AC=4;AF=1;AN=4;AO=6;CIGAR=1X;DP=8;DPB=8;DPRA=0;EPP=16.0391;EPPR=0;GTI=0;LEN=1;MEANALT=2;MQM=42;MQMR=0;NS=2;NUMALT=1;ODDS=9.50932;PAIRED=1;PAIREDR=0;PAO=0;PQA=0;PQR=0;PRO=0;QA=192;QR=0;RO=0;RPP=16.0391;RPPR=0;RUN=1;SAF=6;SAP=16.0391;SAR=0;SRF=0;SRP=0;SRR=0;TYPE=snp;technology.illumina_hi-seq=1;BVAR	GT:DP:RO:QR:AO:QA:GL	1/1:4:0:0:3:96:-5,-0.90309,0	1/1:4:0:0:3:96:-5,-0.90309,0


Questions:

The REF base is picked from hg38.fa?
The ALT would be multiples? so if there are 50 samples in the ALT section would I get 100 genotypes seperated by commas? Say the REF was A and in ALT=T,G,C,A,T ...100 genotypes one from each sample?
Also, what would be present under the heading sample_1 sample_2.

Perhaps what  I need is some hel;p understanding a VCF file with multiple samples generated by freebayes.

**Comment by yaseen-ladak** [comment]
Should the output not be one variant per line in VCF

**Comment by AlistairNWard** [comment]
1. The REF base is taken from the reference you supplied - so, in your
case, yes, it is hg38.fa.
2. The ALT is the alternate allele, and this can be multiple if multiple
alternates are observed. It is not the value seen in each sample. If there
is a SNP, e.g. A->G, the REF is A, the ALT is G and that is all that is
shown. After the format column is the per sample information which will
tell you the genotype of that sample etc.

You should really read the VCF spec. I think it is assumed that when
running variant callers, you need to read some of the basic documentation
to understand the formats and the tools.

https://github.com/ekg/freebayes
https://samtools.github.io/hts-specs/VCFv4.2.pdf


Alistair Ward
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by yaseen-ladak** [comment]
@AlistairNWard @ekg 
Thank you for going out of the way to help me. I was reading the VCF documention. 5.1.1. 
The example they gave was:
#CHROM POS ID REF ALT QUAL FILTER INFO
20 3 . C G . PASS DP=100
20 2 . TC T . PASS DP=100
20 2 . TC TCA . PASS DP=100

Could this not be written as a single statement because in the later example in the VCF documentation 5.1.2 example they use comma separated  and in 5.1.1 they have used as a different record. Are both correct? Alistar this is what you mean by using vt decompose as this will split into separate records?

Just want to make sure I am on the right lines

#CHROM POS ID REF ALT QUAL FILTER INFO
20 2 . TC TG,T, TCA . PASS DP=100

Thanks,
Yaseen
