### ISSUE TITLE
Segmentation Fault in VirtualBox

### ISSUE THREAD

**Issue by Blipblopbloop** [ekg/freebayes#306]
I tried to check for variants between two datasets in BioLinux 8 in VirtualBox. The command I entered is `freebayes -f reference.fasta test_aligned_sorted_marked.bam > var.vcf`.
I received the output `zsh: segmentation fault  freebayes -f reference.fasta  > var.vcf`.
Is this due simply to virtualization? Has anyone else had this problem? I will try running the program directly on the computer as well.

**Comment by lmjakt** [comment]
Generally if you get a segmentation error it is due to a bug in the code; however, that bug may not be triggered on all platforms due to differences in how memory is managed. To find the bug I'd suggest having a look a the core file with gdb or running the process within gdb. To do this you probably want to recompile using 'make debug', after first doing 'make clean'. This will let you know where the program is running into problems and will make it easier to work out what is going on.
Having said that, it is possible to get segmentation errors as a result of running out of heap memory; especially with code the has deep recursion.
To use gdb:
http://www.unknownroad.com/rtfm/gdbtut/gdbadvanced.html#CORE

cheers,
Martin

**Comment by Blipblopbloop** [comment]
Thank you for your suggestion. I resolved the problem with the `unlimit` command prior to running.

**Comment by ekg** [comment]
What did you do with unlimit?

**Comment by lmjakt** [comment]
are you sure you don't mean: ulimit

you can change the maximum size of the stack with ulimit, though I don't remember the details. If you know a particular program is likely to require a bigger stack, you can also call use ulimit from within the program to set user limits (man ulimit). However, the man page tells me that this is now obsolete and that you should instead use setrlimit.

**Comment by Blipblopbloop** [comment]
I am sure that I mean unlimit. I just typed `unlimit` into the terminal and hit enter before I ran FreeBayes. To the best of my knowledge, this removes the limit on use of system resources for the next program that is run.

**Comment by lmjakt** [comment]
That's a new one to me then. Useful information. I've used ulimit
previously for the same purpose, so thought it might be a type.

thanks,

Martin

--
Martin Jakt
Senior Researcher
Marine Genomics Research Group
Faculty of Biosciences and Aquaculture
University of Nordland
P.O. Box 1490, Bodø, Norway
