### ISSUE TITLE
Allele frequencies only 0 and 0.5

### ISSUE THREAD

**Issue by pinkysaid** [ekg/freebayes#392]
Hi,

I'm using FreeBayes to call variants from viral NGS data and I always get AF of 0 and 0.5. This becomes a challenge when carrying out evaluation and analysis.

Is there a way of getting the actual frequencies per position? 

Thanks!

**Comment by GuyReeves** [comment]
I have the same problem any ideas?

**Comment by wangyugui** [comment]
@pinkysaid 

AF=AC/AN
how many samples in your vcf file?

**Comment by GuyReeves** [comment]
Hi 

I resolved this issue a while ago, I think it was actually my misunderstanding .

Thanks

Guy

**Comment by wangyugui** [comment]
Hi. @GuyReeves 

close this issue please.

**Comment by pinkysaid** [comment]
@wangyugui @GuyReeves Thanks!

 Also resorted to calculating it as described above a whiel back.

**Comment by hbeale** [comment]
In my data, I also see that AF=AC/AN, where I would expect it to be AF=AO/DP. I can't tell from this thread whether that is the expected behavior, and if not, will be/has been fixed. Thanks!

from four variants:
AB=0.0909091;ABP=34.9902;AC=1;AF=0.5;AN=2;AO=2;CIGAR=1X;DP=22;
AB=0.046729;ABP=193.958;AC=1;AF=0.5;AN=2;AO=5;CIGAR=1X;DP=107;
AB=0.0416667;ABP=90.593;AC=1;AF=0.5;AN=2;AO=2;CIGAR=1X;DP=48;
AB=0.0869565;ABP=37.093;AC=1;AF=0.5;AN=2;AO=2;CIGAR=1X;DP=23;


For context, we are calling variants in somatic RNA-Seq data; some have weak evidence but are verified in DNA data
