### ISSUE TITLE
Next release tag

### ISSUE THREAD

**Issue by disassembler** [ekg/freebayes#419]
I was able to get freebayes to build with gcc 6 using the latest master, but figuring out how to get 1.1.0 to build is quite a task. Is there any chance of getting a new release tag in git that I can link with the upcoming NixOS 17.09 release?

**Comment by ekg** [comment]
Sure, maybe it's a good time to bump to 1.1.1.

**Comment by wresch** [comment]
I second that. A new tag would be nice.

**Comment by yak1r** [comment]
@ekg  I third that. A new release would be awesome

**Comment by tseemann** [comment]
@ekg I fourth that.  60 commits to master since this release 1.1.0`

I'm ready to get the `conda` and `brew`packages updated when it happens.

**Comment by ekg** [comment]
Ok I'll do this within the coming days. I have a final default parameter
change that I need to set based on a lot of testing and experience.

**Comment by tseemann** [comment]
@ekg It's been 5 days now - any luck finding time?

**Comment by ekg** [comment]
@tseemann yes, but I need to verify changes in https://github.com/ekg/freebayes/pull/453. This caused the tests to fail but I believe it's because the number of variant calls increases.

It would help to have a second, third, and even fourth pair of eyes on those changes. I want to commit them into the release.

Also, I'm concerned about recent reports about freebayes' min alternate fraction filter. I hope you understand that I don't want to cut a release in a buggy state. And also that this isn't my primary work now...

**Comment by tseemann** [comment]
@ekg i'll stop bothering you about it now - i should know better given i have legacy support burden as well.  Your time is better spent on `vg`. I'm looking forward to being able to use it on large sets of bacterial isolates for SNP calling - although i'm not clear how it overlaps with @iqbal-lab work.

**Comment by ekg** [comment]
I've written a response about vg on its issue tracker: https://github.com/vgteam/vg/issues/1589

As for the change at hand I'd like a second pair of eyes before I commit and make a release. That said I'm not going to hold my breath!

I've been running with these settings as my "defaults" for a long time. The only potential problem is that it will force users to post-filter (which they should do anyway given the behavior of freebayes) or they'll get crazy numbers of variant calls.

**Comment by ekg** [comment]
I have tagged v1.2.0. Hope this helps!

**Comment by wresch** [comment]
Great. Thanks
