### ISSUE TITLE
Can i use freebayes in Exome seq pipelines as commercially ?

### ISSUE THREAD

**Issue by anopperl** [ekg/freebayes#434]

**Comment by ekg** [comment]
Yes, of course you can. Many have used and adapted it to this and other commercial contexts. Freebayes is licensed under the MIT license, which is extremely permissive. There are only two things you should do 1) credit the authors by maintaining the copyright and license notice if you redistribute it, 2) waive the authors of all liability for any damages resulting from your use of it. We accept thanks when it does work :) Otherwise you can do anything you want with it. Enjoy!
