### ISSUE TITLE
Allele scope options no longer supported (i.e. --no-mnps and --no-complex)?

### ISSUE THREAD

**Issue by dfajar2** [ekg/freebayes#516]
Hi, 
I just noticed that in the latest release v1.2.0-2-g29c4002 , options such as --no-mnps and --no-complex are no longer supported. Is this related to the comment pasted below, or is it a completely different issue. 
Thanks for your help, and for developing such a great variant caller.

"  These flags are meant for testing.
  They are not meant for filtering the output.
  They actually filter the input to the algorithm by throwing away alignments.
  This hurts performance by hiding information from the Bayesian model.
  Do not use them unless you can validate that they improve results!

   -I --throw-away-snp-obs     Remove SNP observations from input.
   -i --throw-away-indels-obs  Remove indel observations from input.
   -X --throw-away-mnp-obs     Remove MNP observations from input.
   -u --throw-away-complex-obs Remove complex allele observations from input."

**Comment by ekg** [comment]
This is related to this issue.

It can be attractive to use these flags in order to make the VCF simpler to work with, but this is not their intended use.

I wanted users to consider this practice carefully in their application. Furthermore, this clarifies how the original flags were working. They don't just remove data from the output, but from the input, and this can have an impact on variant calling accuracy even for non-complex things.

Please make sure they are doing the right thing in your case. I think they probably do help some applications, so I've left them.

**Comment by dfajar2** [comment]
It makes sense. 
Thanks.
