### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by marcellosforvo** [ekg/freebayes#6]
Hi,
I've run freebayes 3bec28e  with   BWA-generated BAM files and got the following messages for 2 out of 3 samples (3 independent BAM files)  

sample A output:
Exception: Unable to read reference sequence base past end of current cached sequence

sample B otput:
terminate called after throwing an instance of 'std::out_of_range'
 what():  basic_string::substr
Aborted

on the other hand, sample C does not give me error   .

please let me know if any further   information is needed, in case of sample A a specific reference sequence cuases the error an I may report it here or elsewhere as needed

thanks in advance

**Comment by ekg** [comment]
@lkunw  I think that setting ploidy to 100 is possibly going to generate an out-of-memory condition. Did you watch the memory when doing this?

**Comment by KarolinaD** [comment]
Hi,

after running a command "./vcfroc -r hg19.fa -t true_w00.callable_regions.vcf variants_filter_qual20.callable_regions.vcf > true_w00.roc.tsv" I am getting an error of "terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
  Aborted" and I am not quite sure where I might have made a mistake. I saw earlier that a few people had the same problem, that's why I thought that maybe you know now how to solve this?

Cheers,
Karolina
