### ISSUE TITLE
gVCF output support

### ISSUE THREAD

**Issue by boboppie** [ekg/freebayes#76]
Any plan on this? Thanks

**Comment by ekg** [comment]
I've added basic support for gVCF. It's really not sufficient for merging yet, but I'll be working on it to get it to the the point that the output gVCFs can be merged.

Judging by work that @pd3 has been doing on gVCF merging in samtools, gVCF works fine for SNPs, but any time there is ambiguity in allele representation it is effectively impossible to produce a correct representation of a population from only gVCFs. For instance, any indel-containing locus with more than a few different indels is likely to exhibit this kind of problem. As most of the errors that callers make are coming from such regions, I'd imagine the use of gVCF would only complicate things. I don't know if he's ready to share information about this, but it's really impressive.

That all said, there have been a lot of requests for gVCF and as of recently I'm even funded to support it! (Details on that to come!) Also, it's critical to know if a region is covered and if so at what depth, otherwise we have to go back to the input alignments, which I think is really important. So, gVCF output is now part of freebayes. I'll close this issue, and let's describe improvements to the current format in other issues.

**Comment by tantrev** [comment]
Does Freebayes recommend any specific tool for converting .gvcf to .vcf files?

**Comment by ekg** [comment]
Note that freebayes does have rudimentary support for gvcf. Use --gvcf and
--gcvf-chunk-size 1000 for instance.

**Comment by tantrev** [comment]
I guess what I'm trying to say is that bcftools has a (buggy) command "gvcf2vcf" that's supposed to convert .gvcf files to .vcf files.  I was just poking around and couldn't see any obvious way to do the same thing with vcflib?

**Comment by ekg** [comment]
No it may be easiest to write a short script to filter out the lines.
Unfortunately I don't have anything handy.

**Comment by tantrev** [comment]
I'll see if I can whip something up.  Also, just to clarify in your population calling workflow above: would one use the "--report-all-haplotype-alleles" in step 1 to "record a whole-genome coverage map"?

**Comment by elinwang** [comment]
Sorry this may not seem to be the right place to raise the questions. However, I need some clarification related to this issue.

I made a brief summary of the way to handle "n+1 problem" implemented in freebayes and glia process based on @ekg 's comment on Nov 24, 2014 and @tantrev 's last comment.

Steps (without dealing with phased haplotypes):

1. For each sample #i, run freebayes --report-monomorphic to output i.vcf, where i = 1..N. This step is for obtaining whole-genome coverage maps and resulting vcfs are supposed to be very large in size.

2. run vcfcombine 1.vcf 2.vcf, ... N.vcf to get union.vcf (a giant vcf)

3. run glia <parameters> -v union.vcf | freebayes -@union.vcf to output new_i.vcf, where i = 1..N.

4. as a new sample N+1 is added,

    run vcfcombine new_1.vcf  new_2.vcf ... new_N.vcf to get newunion.vcf

    run glia <parameters> -v newunion.vcf | freebayes -@newunion.vcf on sample N+1

My questions are:

    Are the steps described above correct?
    Do I really use the big union.vcf file as a known input?

Many thanks in advance for helping clarify this!
